# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kcoral_gateway_pb2 as kcoral__gateway__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kcoral_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterGatewayStub(object):
    """Service: both streams are initiated by a node, never by the router.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectSupervisor = channel.stream_stream(
                '/kcoral.gateway.v1.RouterGateway/ConnectSupervisor',
                request_serializer=kcoral__gateway__pb2.SupervisorStatus.SerializeToString,
                response_deserializer=kcoral__gateway__pb2.SupervisorAck.FromString,
                _registered_method=True)
        self.ConnectSlot = channel.stream_stream(
                '/kcoral.gateway.v1.RouterGateway/ConnectSlot',
                request_serializer=kcoral__gateway__pb2.SlotFrame.SerializeToString,
                response_deserializer=kcoral__gateway__pb2.SlotFrame.FromString,
                _registered_method=True)


class RouterGatewayServicer(object):
    """Service: both streams are initiated by a node, never by the router.
    """

    def ConnectSupervisor(self, request_iterator, context):
        """Report local health; the router acknowledges registration once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectSlot(self, request_iterator, context):
        """Register one execution slot, then exchange one request at a time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectSupervisor': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectSupervisor,
                    request_deserializer=kcoral__gateway__pb2.SupervisorStatus.FromString,
                    response_serializer=kcoral__gateway__pb2.SupervisorAck.SerializeToString,
            ),
            'ConnectSlot': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectSlot,
                    request_deserializer=kcoral__gateway__pb2.SlotFrame.FromString,
                    response_serializer=kcoral__gateway__pb2.SlotFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kcoral.gateway.v1.RouterGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kcoral.gateway.v1.RouterGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterGateway(object):
    """Service: both streams are initiated by a node, never by the router.
    """

    @staticmethod
    def ConnectSupervisor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kcoral.gateway.v1.RouterGateway/ConnectSupervisor',
            kcoral__gateway__pb2.SupervisorStatus.SerializeToString,
            kcoral__gateway__pb2.SupervisorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectSlot(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kcoral.gateway.v1.RouterGateway/ConnectSlot',
            kcoral__gateway__pb2.SlotFrame.SerializeToString,
            kcoral__gateway__pb2.SlotFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
