"""Self-contained FlashInfer Trace client for benchmark-server."""

from benchmark_server import __version__

from .benchmark import (
    BenchmarkJob,
    BenchmarkProgram,
    DefaultSolutionAdapter,
    DefaultWorkloadInputProvider,
    EvaluationData,
    FlashInferBenchmark,
    FlashInferProgramBuilder,
    FlashInferResultMapper,
    SolutionAdapter,
    UnsupportedFlashInferFeature,
    WorkloadInputProvider,
)
from .models import (
    AxisConst,
    AxisVar,
    BenchmarkConfig,
    BuildSpec,
    Correctness,
    Definition,
    DType,
    Environment,
    EvalConfig,
    Evaluation,
    EvaluationStatus,
    Performance,
    RandomInput,
    ResolvedEvalConfig,
    SafetensorsInput,
    ScalarInput,
    Solution,
    SourceFile,
    SupportedBindings,
    SupportedLanguages,
    TensorSpec,
    Trace,
    TraceSet,
    TraceSetSummary,
    Workload,
)

__all__ = [
    "AxisConst",
    "AxisVar",
    "BenchmarkConfig",
    "BenchmarkJob",
    "BenchmarkProgram",
    "BuildSpec",
    "Correctness",
    "DType",
    "DefaultSolutionAdapter",
    "DefaultWorkloadInputProvider",
    "Definition",
    "Environment",
    "EvalConfig",
    "Evaluation",
    "EvaluationData",
    "EvaluationStatus",
    "FlashInferBenchmark",
    "FlashInferProgramBuilder",
    "FlashInferResultMapper",
    "Performance",
    "RandomInput",
    "ResolvedEvalConfig",
    "SafetensorsInput",
    "ScalarInput",
    "Solution",
    "SolutionAdapter",
    "SourceFile",
    "SupportedBindings",
    "SupportedLanguages",
    "TensorSpec",
    "Trace",
    "TraceSet",
    "TraceSetSummary",
    "UnsupportedFlashInferFeature",
    "Workload",
    "WorkloadInputProvider",
    "__version__",
]
